### PR TITLE
VDOM Util

### PR DESCRIPTION
**Pull request by trieloff**
For #43

### CODE REVIEW

**Comment by trieloff** [comment]
@kptdobe please have a look. 

If we merge this, we can remove `content.htast` and `content.html` (and probably `content.children`) as they are redundant with `content.document`, `content.document.innerHTML` and `content.document.children`.

**Comment by kptdobe** [comment]
ok, I'll review this afternoon.

**Comment by kptdobe** [comment]
I tried the code with the initial project (`hlx demo test`) and the document object contains only an "blank" location object (no children, no innerHTML...)

**Comment by kptdobe** [comment]
It is the "JSONification" of the document object which does not work. A breakpoint in the `pre.js` shows me the content.document object full of stuff!

**Comment by trieloff** [comment]
The basic motivation for this is outlined in @simonwex's issue adobe/project-helix#305:

> #### Mark
> Mark is using Helix to power the adobe.io website by outputting HTML
> Mark needs to restructure the content to efficiently produce attractive layouts without the adobe.io content authors having to have special formatting knowledge
> - When styling the content, he uses CSS selectors to identify content
> - When manipulating the content structure, he works with the DOM API

So the idea is to give Mark an API for manipulating HTML that he is familiar with, instead of forcing him to learn HTAST (as great as it might be with all the unist-utils) or any new content structure (that we haven't defined in more than a couple of months, see #24)

> we now have a huge content.document object which is a representation of the browser DOM, including all events (`onmousemove`…) which is completely useless.

It might be useless, but I'd argue there is little harm done and it can increase compatibility when the developer is introducing their favorite library that happens to access `onmousemove` without any guards.

> I still do not understand who is going to use things like `content.document.getElementsByTagName('h1')` and to do what... My assumption is that a web developer will want to work with HTL and a developer preparing the data or convertir the sections into something project specific might want to go more for a simplified version of the mdast, basically a json representation.

Below are a couple of examples of how I could see this play out. They all have in common that the developer does not want to touch anything that looks like Markdown, but is very familiar with the DOM.

### Super Simple

Mark is fine with the HTML content and just wants it printed as is:

```html
<body>
${content.document.innerHTML}
</body>
```

Easy.

### Wrapping top-level elements

This replaces the `it.children` iterator.
```html
<div data-sly-list="${content.document.childNodes}">${item.innerHTML}</div>
```

### Adjusting Headlines

This takes a little work in `pre.js`:

```javascript
// remove the first heading
const firstheading = content.document.querySelector('h1');
firstheading.parentNode.removeChild(firstheading);

// downgrade all remaining h1 to h2
content.document.getElementsByTagName('h1').map(heading => {
  heading.outerHTML = '<h2>' + heading.innerHTML + '</h2>';
});
```

```html
<body>
<h1 class="myheading">${content.meta.title}</h1>
${content.document.innerHTML}
</body>
```

In all examples, you could even prototype the code on the client, in the web developer console before moving it server-side.

**Comment by simonwex** [comment]
This is much tidier than I thought it would be. You nailed the use-case. Nice work!

I'll try to use it for real at some point this week, but from my static inspection, it looks like a great candidate to merge.

**Comment by trieloff** [comment]
@kptdobe @simonwex I'm putting this back in WIP, as I noticed that the PR would break the image responsifyer, which is working on HTAST. I will need to re-implement that on top of the new DOM.

**Comment by trieloff** [comment]
Some more documentation to describe how custom sizes for responsive images can be created.

**Pull request merged**
