### PR TITLE
Extract Sections and set section-specific metadata properties

### LINKED ISSUE #42: Extract Sections (with metadata) from Markdown
See adobe/project-helix#305

### PR DESCRIPTION
**Pull request by trieloff**
This is a WIP, waiting for remarkjs/remark-frontmatter#6 to get merged.

This PR:
- adds a new property: `content.sections`, which is an Array of `Section` nodes, with each section
  - having an optional `meta` property with section-specific metadata, if the section has been created through a YAML block
  - having an `intro` and`title` property, using the first paragraph and heading of the section
  - having an `image` property, pointing to the `url` of the first image
  - having a `types` array that describes the content that can be found inside the section, using following patterns:
    - `has-<type>`: for each type of content that occurs at least once in the section, e.g. `has-heading`
    - `is-<type>-only`: for sections that only have content of a single type, e.g. `is-image-only`
    - `is-<type-1>-<type-2>-<type3>`, `is-<type-1>-<type-2>`, and `is-<type-1>` for the top 3 most frequent types of children in the section. For instance a gallery with a heading and description would be `is-image-paragraph-heading`.
 - takes `content.meta` as an aggregation of all `section` `meta` objects (same behavior as before)
 - copies `intro` and `title` from the first `section` (same as before)
 - copies `image` from the first section that has an image

Fixes #42

### CODE REVIEW

**Comment by kptdobe** [comment]
Tested this PR on "my" sample project and it crashes while rendering this md file: https://github.com/kptdobe/helix-bootstrap-grayscale/blob/master/index.md

```
 error: Error while delivering resource /index.html - YAMLException: tag suffix cannot contain flow indicator characters at line 4, column 50:
     ... pg](/dist/img/demo-image-01.jpg)
                                         ^
    at generateError (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readTagProperty (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1173:7)
    at composeNode (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1298:12)
    at readDocument (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at safeLoad (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at yamls.map (/Users/alex/work/dev/helix/project-helix/modules/hypermedia-pipeline/src/html/get-metadata.js:18:43)
```

**Comment by kptdobe** [comment]
This goes into the direction I would like to take but this has some flaws:

1. the `Section` nodes are an hybrid mix between an homemade object and mdast nodes as children. 
  a. If we make it an mdast extension, it needs have a root and Section needs to have its own spec (see https://github.com/syntax-tree/mdast)
  b. It could be a pure object, which makes things much easier to consume in HTL, but then the children must be converted to pure object too. And here, a cleaned up hast is much closer to what we would need
2. If we have 1b, we do not need the hast object at all or have to deal with mdast -> hast -> html conversions: we can consume the pure object in the HTL. I tried this PR with "my" bootstrap sample and htl templates, works fine.

**Comment by trieloff** [comment]
@kptdobe can you replace your `---` with `***` - that should be a quick fix for the YAML parser.

**Comment by trieloff** [comment]
@kptdobe 1) I would simply rename the type from `section` to `root` - then they are valid MDAst nodes.

**Comment by trieloff** [comment]
@kptdobe 2) I see sections as a markdown-level concept. For the question on how to make the HTML more bearable, I'd look at #43

**Pull request merged**
